### PR TITLE
Add country to the Directory page search results

### PR DESCRIPTION
**Pull request by sebastiantecsi**
## Description
Add country to the Directory page search results
- add computed field _content to contain Sitecore Fields: Country, FirstName and LastName
- extend facets for the frontend to include Country
- change scss for search-results so that near the Country of a person an icon with a globe is shown
- add icon globe

## Motivation
Show what country is each person and display a facet for the country too. 
Will give you great help to see persons from a certain country. 
Also gives the possibility to search for a country

## How Has This Been Tested?
- added few persons with different countries setup
- added a person that has no country setup
- publish and re-index sitecore_web_index to make sure that the new computed field is indexed
- manual testing in the frontend

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:

- [x] I have read the Contributing guide.
- [x] My code follows the code style of this project.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

### CODE REVIEW

**Comment by sebastiantecsi** [comment]
Please make sure to re-index sitecore_web_index to make sure that the new computed field is indexed when things are deployed
And on my local looks like here:

2022-01-27_23h37_36

**Comment by GoranHalvarsson** [comment]
Would be nice if you guys could get it in :-)
So we can filter by country

**Review by robearlam — APPROVED** [review]

**Comment by cassidydotdk** [comment]
There is a slight issue here, in how this data is organised. Some of us (myself included) have been awarded MVP in multiple countries. Not in the same year obviously, but over time. So for some years, my MVP title is "tied" to the UK, for others, Switzerland. There are not many of us, but I know this is also the case for e.g. Marek Musielak

**Comment by ahmed-ae** [comment]
@cassidydotdk I think @mrtamasvarga  wanted the country to reflect your current residence (country) and not to store the historical changes in the person's country of residence.

**Pull request merged**
