### PR TITLE
Use Microsoft.Build.CentralPackageVersions

### PR DESCRIPTION
**Pull request by anderslaub**
## Description
As title says; this should be the default common practice, always centralize packageref versioning.

Also note that all platform projects was referencing 10.0 and not 10.1... These kind of missing version updates are much harder to miss when using central package versioning..

## Motivation
Makes the upgrade to 10.2 x100 times faster and developers x1000 times happier.

## How Has This Been Tested?
The solution and images builds.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:
- [x] I have read the Contributing guide.
- [x] My code follows the code style of this project.
- [x] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

### CODE REVIEW

**Comment by ahmed-ae** [comment]
Did you confirm that solution image can be built? I tried this before but msbuild commands were failing

i will pull this branch and confirm

**Comment by anderslaub** [comment]
I'll just double check.. I might have missed a change to a Dockerfile in commit, 2 min.

**Comment by anderslaub** [comment]
@ahmed-ae sorry, I was missing a file in the commit.

**Comment by anderslaub** [comment]
Abandoning this PR. Will make a new one with centralpackageversioning, sdk style projects everywhere and simplistic publishing with no hpp

**Pull request closed without merging**
