### PR TITLE
generates sitemap.xml  and displays it on accessing sitemap.xml url

### PR DESCRIPTION
**Pull request by navancommits**
Generates sitemap.xml  for the site

## Description
Generates and stores the sitemap.xml when any of the site pages loads then displays the sitemap.xml when the url is accessed, blogged here:
https://navansitecorenotes.blogspot.com/2022/01/how-to-generate-sitemapxml-for-sitecore.html

## Motivation
It is part of requested enhancements 

## How Has This Been Tested?
Details here:
https://navansitecorenotes.blogspot.com/2022/01/how-to-generate-sitemapxml-for-sitecore.html

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation update (non-breaking change; modified files are limited to the `/docs` directory)

## Checklist:

- [ x] I have read the Contributing guide.
- [x ] My code follows the code style of this project.
- [ x] My code/comments/docs fully adhere to the Code of Conduct.
- [ ] My change is a code change and it requires an update to the documentation.
- [ ] My change is a documentation change and it requires an update to the navigation.

### CODE REVIEW

**Comment by dylanyoung-dev** [comment]
Alright I've reviewed the blog post you wrote @navancommits, as well as the commits highlighted above.  I must say, a creative approach, but I'm not too sure it solves all the concerns.  Took a little effort to wrap my mind around it, considering the circumstances of this being a headless implementation.  So before I provide suggestions, I just want to ensure I understand all of your logic correctly.  So I see the pipeline that will run on HttpBeginRequest.  It appears this would run on the CM/CD environments?  It looks like you then enter Docker into the mix.  It uses the volume mounting to take what is generated and automatically is moved into the rendering host?

There is a few issues with this approach.  The more obvious is that this wouldn't work that great in a multi-site scenario.  You are generating a single xml that would be passed onto each of the rendering host environments.  Also I'm not sure Docker is the right approach.  It works locally, but would be different in a production environment.  Example the CM and Rendering Hosts could be different environments (linux vs windows - I haven't checked how AKS is configured but with .net core it's possible), but also likely wouldn't have the same volume mounts defined.  You could theoretically create a blob storage that they both share, but would require new configuration to support.

Also not sure I'd want this as part of the begin request, would think it makes more sense in the publishing process?  Because it only changes on publishing.

Also noticed this defines a robot.txt for this flow.  Which I would think this should be handled by the rendering host.  And then also pondering if everything should be handled by the rendering host.  Maybe call a process in the CD to get back all the paths for the current context site and then use that to generate the xml file or cache it on the server.  And then re-run the check for new links (or likely just a process to get all pages and regenerate the xml sitemap).

**Comment by navancommits** [comment]
Sure,  will re-write and update the branch....

**Comment by robearlam** [comment]
I just spoke with @navancommits about this. Instead of building something from scratch, it would be good to see if we can leverage the `GraphQLSitemapService` that is part of JSS used to handle Sitemap generation for NextJs sites. It might not be 100% compatible, but it would be good to see if we could base our solution of it.

Details here: https://doc.sitecore.com/xp/en/developers/hd/190/sitecore-headless-development/preparing-the-list-of-pages-for-static-generation-or-export-in-jss-next-js-apps.html

**Comment by navancommits** [comment]
Sure, seems interesting, will give it a try....

**Comment by robearlam** [comment]
Closed as this repository is being archived.

**Pull request closed without merging**
